import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Product-centric IA: Introduction → Quickstart → Concepts → product areas → Guides → SDKs → Integrations → Security → Reference
 */
const sidebars: SidebarsConfig = {
    docs: [
        "intro",
        {
            type: "category",
            label: "Quickstart",
            link: { type: "doc", id: "quickstart/index" },
            items: ["quickstart/humans", "quickstart/agents"],
        },
        {
            type: "category",
            label: "Concepts",
            link: { type: "doc", id: "concepts/what-is-1claw" },
            items: [
                "concepts/parts-of-1claw",
                "concepts/hsm-architecture",
                "concepts/secrets-model",
                "concepts/human-vs-agent-api",
                "concepts/trust-model",
                "concepts/licensing",
            ],
        },
        {
            type: "category",
            label: "Vaults",
            link: { type: "doc", id: "vaults/overview" },
            collapsed: false,
            items: [
                "vaults/golden-path",
                "vaults/securing-access",
                "vaults/scoped-permissions",
                "vaults/revoking-access",
                "vaults/rotating-secrets",
                "vaults/rotation-bindings",
                "vaults/cmek",
                "vaults/mpc",
                {
                    type: "category",
                    label: "Human API",
                    link: { type: "doc", id: "vaults/human-api/overview" },
                    items: [
                        "vaults/human-api/authentication",
                        {
                            type: "category",
                            label: "Secrets",
                            items: [
                                "vaults/human-api/secrets/create",
                                "vaults/human-api/secrets/read",
                                "vaults/human-api/secrets/update",
                                "vaults/human-api/secrets/delete",
                                "vaults/human-api/secrets/rotate",
                            ],
                        },
                        {
                            type: "category",
                            label: "Grants (Policies)",
                            items: [
                                "vaults/human-api/grants/create-grant",
                                "vaults/human-api/grants/revoke-grant",
                                "vaults/human-api/grants/list-grants",
                            ],
                        },
                        {
                            type: "category",
                            label: "Agents",
                            items: [
                                "vaults/human-api/agents/register-agent",
                                "vaults/human-api/agents/list-agents",
                                "vaults/human-api/agents/deactivate-agent",
                            ],
                        },
                        "vaults/human-api/errors",
                    ],
                },
                {
                    type: "category",
                    label: "MCP Server",
                    link: { type: "doc", id: "vaults/mcp/overview" },
                    items: [
                        "vaults/mcp/setup",
                        "vaults/mcp/tools",
                        "vaults/mcp/security",
                        "vaults/mcp/deployment",
                    ],
                },
            ],
        },
        {
            type: "category",
            label: "Agents",
            link: { type: "doc", id: "agents/overview" },
            collapsed: false,
            items: [
                "agents/self-enrollment",
                "agents/fleet-management",
                "agents/delegation",
                "agents/discovery",
                "agents/memory",
                "agents/communication",
                "agents/channels",
                "agents/bankr-keys",
                "agents/oidc-federation",
                {
                    type: "category",
                    label: "Shroud (LLM proxy)",
                    link: { type: "doc", id: "agents/shroud/overview" },
                    items: [
                        "agents/shroud/threat-detection",
                        "agents/shroud/configuration",
                        "agents/shroud/ide-setup",
                    ],
                },
                {
                    type: "category",
                    label: "Intents (signing)",
                    link: { type: "doc", id: "agents/intents/overview" },
                    items: [
                        "agents/intents/signing",
                        "agents/intents/guardrails",
                        "agents/intents/multi-chain-signing",
                        "agents/intents/crypto-proxy-legacy",
                    ],
                },
                {
                    type: "category",
                    label: "Agent API",
                    link: { type: "doc", id: "agents/api/overview" },
                    items: [
                        "agents/api/authentication",
                        "agents/api/fetch-secret",
                        "agents/api/list-accessible-secrets",
                        "agents/api/audit-log",
                        "agents/api/errors",
                    ],
                },
            ],
        },
        {
            type: "category",
            label: "Automations",
            link: { type: "doc", id: "automations/overview" },
            items: [],
        },
        {
            type: "category",
            label: "Runtimes",
            link: { type: "doc", id: "runtimes/overview" },
            items: ["runtimes/hosting"],
        },
        {
            type: "category",
            label: "Cards",
            link: { type: "doc", id: "cards/overview" },
            items: [],
        },
        {
            type: "category",
            label: "Treasury",
            link: { type: "doc", id: "treasury/overview" },
            collapsed: false,
            items: [
                "treasury/embedded-wallets",
                "treasury/wallet-react",
                "treasury/safe-multisig",
                "treasury/account-abstraction",
                "treasury/approvals",
                "treasury/policy-engine",
            ],
        },
        {
            type: "category",
            label: "Sharing",
            link: { type: "doc", id: "sharing/overview" },
            items: [],
        },
        {
            type: "category",
            label: "Risk Engine",
            link: { type: "doc", id: "risk-engine/overview" },
            items: [],
        },
        {
            type: "category",
            label: "Platform API",
            link: { type: "doc", id: "platform-api/overview" },
            items: [
                "platform-api/multi-tenant",
                "platform-api/webhooks",
                "platform-api/oauth-connections",
            ],
        },
        {
            type: "category",
            label: "Dashboard",
            link: { type: "doc", id: "dashboard/overview" },
            items: [
                "dashboard/vaults-secrets",
                "dashboard/agents-policies",
                "dashboard/treasury-cards",
                "dashboard/settings-billing",
                "dashboard/platform-wizard",
            ],
        },
        {
            type: "category",
            label: "Guides",
            link: {
                type: "generated-index",
                title: "Guides",
                description: "Cross-cutting workflows: setup, billing, compliance, troubleshooting.",
                slug: "/category/guides",
            },
            items: [
                "guides/setup-by-client",
                "guides/five-minute-walkthrough",
                "guides/billing-and-usage",
                "guides/x402",
                "guides/deploying-updates",
                "guides/audit-and-compliance",
                "guides/email-notifications",
                "guides/troubleshooting",
                "guides/principal-type-audit",
            ],
        },
        {
            type: "category",
            label: "SDKs",
            link: { type: "doc", id: "sdks/overview" },
            items: ["sdks/javascript", "sdks/python", "sdks/go", "sdks/curl-examples"],
        },
        {
            type: "category",
            label: "Integrations",
            link: { type: "doc", id: "integrations/overview" },
            items: [
                {
                    type: "category",
                    label: "Official packages",
                    items: ["integrations/langchain", "integrations/crewai"],
                },
                "integrations/mcp-integration",
                "integrations/mcp-deep-dive",
                "integrations/cli",
                "integrations/agent-frameworks",
                "integrations/ai-sdk-integration",
                "integrations/openclaw",
                "integrations/openclaw-plugin",
                "integrations/elizaos",
                "integrations/scaffold-agent",
                "integrations/base-mcp-secure",
                "integrations/claude-code",
                "integrations/agent-templates",
                "integrations/ecosystem",
                {
                    type: "category",
                    label: "Wallet & key migrations",
                    items: [
                        "integrations/migrate-from-dynamic",
                        "integrations/migrate-from-privy",
                        "integrations/migrate-from-turnkey",
                        "integrations/web3auth",
                        "integrations/thirdweb",
                        "integrations/magic",
                        "integrations/fireblocks",
                        "integrations/coinbase-smart-wallet",
                        "integrations/wagmi-rainbowkit",
                    ],
                },
            ],
        },
        {
            type: "category",
            label: "Security",
            items: [
                "security/hsm-overview",
                "security/key-hierarchy",
                "security/agent-keys",
                "security/zero-trust",
                "security/two-factor-auth",
                "security/compliance",
            ],
        },
        {
            type: "category",
            label: "Reference",
            items: [
                "reference/api-reference",
                "reference/request-pipeline",
                "reference/shroud-supported-models",
                "reference/api-mcp-testing",
                "reference/error-codes",
                "reference/rate-limits",
                "reference/glossary",
                "reference/changelog",
                "reference/changelog-2026",
            ],
        },
    ],
};

export default sidebars;
